version: '3.7'

services:

  server:
    image: backend
    container_name: 'cloud-storage-server'
    build: ./
    ports:
      - "8888:8888"
    depends_on:
      - database
    environment:
      PORT: 8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres

  database:
    image: postgres:alpine
    container_name: postgres

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres